Stashed testing

diff --git a/judge/create_cgroups.in b/judge/create_cgroups.in
--- a/judge/create_cgroups.in
+++ b/judge/create_cgroups.in
@@ -20,23 +20,23 @@ print_cgroup_instruction () {
     exit 1
 }
 
-for i in cpuset memory; do
-    mkdir -p $CGROUPBASE/$i
-    if [ ! -d $CGROUPBASE/$i/ ]; then
-        if ! mount -t cgroup -o$i $i $CGROUPBASE/$i/; then
-            echo "Error: Can not mount $i cgroup. Probably cgroup support is missing from running kernel. Unable to continue."
-            print_cgroup_instruction
-        fi
-    fi
-    mkdir -p $CGROUPBASE/$i/domjudge
-done
+#for i in cpuset; do
+#    mkdir -p $CGROUPBASE/$i
+#    if [ ! -d $CGROUPBASE/$i/ ]; then
+#        if ! mount -t cgroup -o$i $i $CGROUPBASE/$i/; then
+#            echo "Error: Can not mount $i cgroup. Probably cgroup support is missing from running kernel. Unable to continue."
+#            print_cgroup_instruction
+#        fi
+#    fi
+#    mkdir -p $CGROUPBASE/$i/domjudge
+#done
 
-if [ ! -f $CGROUPBASE/memory/memory.limit_in_bytes ] || [ ! -f $CGROUPBASE/memory/memory.memsw.limit_in_bytes ]; then
-    echo "Error: cgroup support missing memory features in running kernel. Unable to continue."
-    print_cgroup_instruction
-fi
+#if [ ! -f $CGROUPBASE/memory/memory.limit_in_bytes ] || [ ! -f $CGROUPBASE/memory/memory.memsw.limit_in_bytes ]; then
+#    echo "Error: cgroup support missing memory features in running kernel. Unable to continue."
+#    print_cgroup_instruction
+#fi
 
-chown -R $JUDGEHOSTUSER $CGROUPBASE/*/domjudge
+#chown -R $JUDGEHOSTUSER $CGROUPBASE/*/domjudge
 
-cat $CGROUPBASE/cpuset/cpuset.cpus > $CGROUPBASE/cpuset/domjudge/cpuset.cpus
-cat $CGROUPBASE/cpuset/cpuset.mems > $CGROUPBASE/cpuset/domjudge/cpuset.mems
+#cat $CGROUPBASE/cpuset/cpuset.cpus > $CGROUPBASE/cpuset/domjudge/cpuset.cpus
+#cat $CGROUPBASE/cpuset/cpuset.mems > $CGROUPBASE/cpuset/domjudge/cpuset.mems
