Better document the used new cgroup

diff --git a/judge/create_cgroups.in b/judge/create_cgroups.in
--- a/judge/create_cgroups.in
+++ b/judge/create_cgroups.in
@@ -64,6 +64,16 @@ done
 #    fi
 #    mkdir -p $CGROUPBASE/$i/domjudge
 #done
+for i in cpuset memory; do
+    mkdir -p $CGROUPBASE/$i
+    if [ ! -d $CGROUPBASE/$i/ ]; then
+        if ! mount -t cgroup -o$i $i $CGROUPBASE/$i/; then
+            echo "Error: Can not mount $i cgroup. Probably cgroup support is missing from running kernel. Unable to continue."
+            print_cgroup_instruction
+        fi
+    fi
+    mkdir -p $CGROUPBASE/$i/$CGROUP_DIR
+done
 
 #if [ ! -f $CGROUPBASE/memory/memory.limit_in_bytes ] || [ ! -f $CGROUPBASE/memory/memory.memsw.limit_in_bytes ]; then
 #    echo "Error: cgroup support missing memory features in running kernel. Unable to continue."
@@ -79,3 +89,7 @@ done
 
 #cat $CGROUPBASE/cpuset/cpuset.cpus > $CGROUPBASE/cpuset/domjudge/cpuset.cpus
 #cat $CGROUPBASE/cpuset/cpuset.mems > $CGROUPBASE/cpuset/domjudge/cpuset.mems
+#chown -R $JUDGEHOSTUSER $CGROUPBASE/*/$CGROUP_DIR
+#
+#cat $CGROUPBASE/cpuset/cpuset.cpus > $CGROUPBASE/cpuset/$CGROUP_DIR/cpuset.cpus
+#cat $CGROUPBASE/cpuset/cpuset.mems > $CGROUPBASE/cpuset/$CGROUP_DIR/cpuset.mems
